### PR TITLE
refactor controllers

### PR DESCRIPTION
**Pull request by mustafa-korkmaz**
- Remove redundant IHttpContextAccessor
- Remove redundant userId path on UserController.

### CODE REVIEW

**Comment by yusufyilmazfr** [comment]
**User** already provides HttpContext?.User. It looks well! 🎉

```csharp
/// <summary>
/// Gets the <see cref="ClaimsPrincipal"/> for user associated with the executing action.
/// </summary>
public ClaimsPrincipal User => HttpContext?.User;
```

But, I found a few things in the commits. Why did you delete route parameter in route? For example, UserId looks unnecessary but I have used it for naming convention.

[Route("/users/{userId}/change-password")] means there is a userId who wants to change the password.

**Review by furkandeveloper — APPROVED** [review]
:lgtm:

**Comment by mustafa-korkmaz** [comment]
> **User** already provides HttpContext?.User. It looks well! 🎉
> 
> ```cs
> /// <summary>
> /// Gets the <see cref="ClaimsPrincipal"/> for user associated with the executing action.
> /// </summary>
> public ClaimsPrincipal User => HttpContext?.User;
> ```
> 
> But, I found a few things in the commits. Why did you delete route parameter in route? For example, UserId looks unnecessary but I have used it for naming convention.
> 
> [Route("/users/{userId}/change-password")] means there is a userId who wants to change the password.

If you want a naming convention you can use something like `/users/me` but current one looks pointless. What ever you pass as a route parameter it will be overridden by `User.Claims.GetUserId()`

**Comment by yusufyilmazfr** [comment]
You're right! I will merge it.

**Comment by yusufyilmazfr** [comment]
Thanks for your contribution. 🎉

**Pull request merged**
